version: '3.1'
services:
  bot:
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - 3000:3000
    env_file:
      - ./config/bot.env
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - slack_gcal

  db:
    image: postgres:11
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./config/db.env
    networks:
      - slack_gcal

networks:
  slack_gcal:

volumes:
  node_modules:
  postgres_data:
