version: '3.1'
services:
  bot:
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: slack
      POSTGRES_PASSWORD: slack
      POSTGRES_HOST: db
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules

  db:
    image: postgres:11
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=slack
      - POSTGRES_PASSWORD=slack
      - POSTGRES_DB=slack
    networks:
      - slack_gcal

networks:
  slack_gcal:

volumes:
  node_modules:
  postgres_data:
